//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private string fимя;
        
        private string fфамилия;
        
        private string fотчетство;
        
        private int fномер;
        
        private IIS.1.Должности fДолжности;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// имя.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.имя CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.имя CustomAttributes)
        [StrLen(255)]
        public virtual string имя
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.имя Get start)

                // *** End programmer edit section *** (Сотрудник.имя Get start)
                string result = this.fимя;
                // *** Start programmer edit section *** (Сотрудник.имя Get end)

                // *** End programmer edit section *** (Сотрудник.имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.имя Set start)

                // *** End programmer edit section *** (Сотрудник.имя Set start)
                this.fимя = value;
                // *** Start programmer edit section *** (Сотрудник.имя Set end)

                // *** End programmer edit section *** (Сотрудник.имя Set end)
            }
        }
        
        /// <summary>
        /// номер.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.номер CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.номер CustomAttributes)
        public virtual int номер
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.номер Get start)

                // *** End programmer edit section *** (Сотрудник.номер Get start)
                int result = this.fномер;
                // *** Start programmer edit section *** (Сотрудник.номер Get end)

                // *** End programmer edit section *** (Сотрудник.номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.номер Set start)

                // *** End programmer edit section *** (Сотрудник.номер Set start)
                this.fномер = value;
                // *** Start programmer edit section *** (Сотрудник.номер Set end)

                // *** End programmer edit section *** (Сотрудник.номер Set end)
            }
        }
        
        /// <summary>
        /// отчетство.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.отчетство CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.отчетство CustomAttributes)
        [StrLen(255)]
        public virtual string отчетство
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.отчетство Get start)

                // *** End programmer edit section *** (Сотрудник.отчетство Get start)
                string result = this.fотчетство;
                // *** Start programmer edit section *** (Сотрудник.отчетство Get end)

                // *** End programmer edit section *** (Сотрудник.отчетство Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.отчетство Set start)

                // *** End programmer edit section *** (Сотрудник.отчетство Set start)
                this.fотчетство = value;
                // *** Start programmer edit section *** (Сотрудник.отчетство Set end)

                // *** End programmer edit section *** (Сотрудник.отчетство Set end)
            }
        }
        
        /// <summary>
        /// фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.фамилия CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.фамилия Get start)

                // *** End programmer edit section *** (Сотрудник.фамилия Get start)
                string result = this.fфамилия;
                // *** Start programmer edit section *** (Сотрудник.фамилия Get end)

                // *** End programmer edit section *** (Сотрудник.фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.фамилия Set start)

                // *** End programmer edit section *** (Сотрудник.фамилия Set start)
                this.fфамилия = value;
                // *** Start programmer edit section *** (Сотрудник.фамилия Set end)

                // *** End programmer edit section *** (Сотрудник.фамилия Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Должности CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.1.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Должности Get start)

                // *** End programmer edit section *** (Сотрудник.Должности Get start)
                IIS.1.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Сотрудник.Должности Get end)

                // *** End programmer edit section *** (Сотрудник.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Должности Set start)

                // *** End programmer edit section *** (Сотрудник.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Сотрудник.Должности Set end)

                // *** End programmer edit section *** (Сотрудник.Должности Set end)
            }
        }
    }
}
