//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Бригадир.
    /// </summary>
    // *** Start programmer edit section *** (Бригадир CustomAttributes)

    // *** End programmer edit section *** (Бригадир CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Бригадир : IIS.1.Сотрудник
    {
        
        // *** Start programmer edit section *** (Бригадир CustomMembers)

        // *** End programmer edit section *** (Бригадир CustomMembers)

    }
}
