//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ВнешнийПользователь.
    /// </summary>
    // *** Start programmer edit section *** (ВнешнийПользователь CustomAttributes)

    // *** End programmer edit section *** (ВнешнийПользователь CustomAttributes)
    public interface ВнешнийПользователь
    {
        
        // *** Start programmer edit section *** (ВнешнийПользователь CustomMembers)

        // *** End programmer edit section *** (ВнешнийПользователь CustomMembers)

        
        /// <summary>
        /// ВнешнийПользователь.
        /// </summary>
        // *** Start programmer edit section *** (ФормаТабеля CustomAttributes)

        // *** End programmer edit section *** (ФормаТабеля CustomAttributes)
        IIS.1.ФормаТабеля ФормаТабеля
        {
            get;
            set;
        }
    }
}
