//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ГрафикРаботыСотрудника.
    /// </summary>
    // *** Start programmer edit section *** (ГрафикРаботыСотрудника CustomAttributes)

    // *** End programmer edit section *** (ГрафикРаботыСотрудника CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ГрафикРаботыСотрудника : ICSSoft.STORMNET.DataObject
    {
        
        private double fчислоЧасов;
        
        private System.DateTime fвремяНачала;
        
        private System.DateTime fвремяОкончания;
        
        private IIS.1.ТабельСмены fТабельСмены;
        
        private IIS.1.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (ГрафикРаботыСотрудника CustomMembers)

        // *** End programmer edit section *** (ГрафикРаботыСотрудника CustomMembers)

        
        /// <summary>
        /// времяНачала.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботыСотрудника.времяНачала CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботыСотрудника.времяНачала CustomAttributes)
        public virtual System.DateTime времяНачала
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.времяНачала Get start)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.времяНачала Get start)
                System.DateTime result = this.fвремяНачала;
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.времяНачала Get end)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.времяНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.времяНачала Set start)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.времяНачала Set start)
                this.fвремяНачала = value;
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.времяНачала Set end)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.времяНачала Set end)
            }
        }
        
        /// <summary>
        /// времяОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботыСотрудника.времяОкончания CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботыСотрудника.времяОкончания CustomAttributes)
        public virtual System.DateTime времяОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.времяОкончания Get start)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.времяОкончания Get start)
                System.DateTime result = this.fвремяОкончания;
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.времяОкончания Get end)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.времяОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.времяОкончания Set start)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.времяОкончания Set start)
                this.fвремяОкончания = value;
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.времяОкончания Set end)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.времяОкончания Set end)
            }
        }
        
        /// <summary>
        /// числоЧасов.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботыСотрудника.числоЧасов CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботыСотрудника.числоЧасов CustomAttributes)
        public virtual double числоЧасов
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.числоЧасов Get start)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.числоЧасов Get start)
                double result = this.fчислоЧасов;
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.числоЧасов Get end)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.числоЧасов Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.числоЧасов Set start)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.числоЧасов Set start)
                this.fчислоЧасов = value;
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.числоЧасов Set end)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.числоЧасов Set end)
            }
        }
        
        /// <summary>
        /// ГрафикРаботыСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботыСотрудника.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботыСотрудника.Сотрудник CustomAttributes)
        [PropertyStorage("Сотрудник")]
        [TypeUsage(new string[] {
                "IIS.1.Бригадир",
                "IIS.1.Работник",
                "IIS.1.Сотрудник"})]
        [NotNull()]
        public virtual IIS.1.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.Сотрудник Get start)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.Сотрудник Get start)
                IIS.1.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.Сотрудник Get end)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.Сотрудник Set start)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.Сотрудник Set end)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// ГрафикРаботыСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботыСотрудника.ТабельСмены CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботыСотрудника.ТабельСмены CustomAttributes)
        [PropertyStorage(new string[] {
                "ТабельСмены"})]
        [NotNull()]
        public virtual IIS.1.ТабельСмены ТабельСмены
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.ТабельСмены Get start)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.ТабельСмены Get start)
                IIS.1.ТабельСмены result = this.fТабельСмены;
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.ТабельСмены Get end)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.ТабельСмены Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.ТабельСмены Set start)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.ТабельСмены Set start)
                this.fТабельСмены = value;
                // *** Start programmer edit section *** (ГрафикРаботыСотрудника.ТабельСмены Set end)

                // *** End programmer edit section *** (ГрафикРаботыСотрудника.ТабельСмены Set end)
            }
        }
    }
}
