//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должности.
    /// </summary>
    // *** Start programmer edit section *** (Должности CustomAttributes)

    // *** End programmer edit section *** (Должности CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Должности : ICSSoft.STORMNET.DataObject
    {
        
        private string fкод;
        
        private string fнаименование;
        
        // *** Start programmer edit section *** (Должности CustomMembers)

        // *** End programmer edit section *** (Должности CustomMembers)

        
        /// <summary>
        /// код.
        /// </summary>
        // *** Start programmer edit section *** (Должности.код CustomAttributes)

        // *** End programmer edit section *** (Должности.код CustomAttributes)
        [StrLen(255)]
        public virtual string код
        {
            get
            {
                // *** Start programmer edit section *** (Должности.код Get start)

                // *** End programmer edit section *** (Должности.код Get start)
                string result = this.fкод;
                // *** Start programmer edit section *** (Должности.код Get end)

                // *** End programmer edit section *** (Должности.код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.код Set start)

                // *** End programmer edit section *** (Должности.код Set start)
                this.fкод = value;
                // *** Start programmer edit section *** (Должности.код Set end)

                // *** End programmer edit section *** (Должности.код Set end)
            }
        }
        
        /// <summary>
        /// наименование.
        /// </summary>
        // *** Start programmer edit section *** (Должности.наименование CustomAttributes)

        // *** End programmer edit section *** (Должности.наименование CustomAttributes)
        [StrLen(255)]
        public virtual string наименование
        {
            get
            {
                // *** Start programmer edit section *** (Должности.наименование Get start)

                // *** End programmer edit section *** (Должности.наименование Get start)
                string result = this.fнаименование;
                // *** Start programmer edit section *** (Должности.наименование Get end)

                // *** End programmer edit section *** (Должности.наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.наименование Set start)

                // *** End programmer edit section *** (Должности.наименование Set start)
                this.fнаименование = value;
                // *** Start programmer edit section *** (Должности.наименование Set end)

                // *** End programmer edit section *** (Должности.наименование Set end)
            }
        }
    }
}
