//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ОтсутствиеСотрудника.
    /// </summary>
    // *** Start programmer edit section *** (ОтсутствиеСотрудника CustomAttributes)

    // *** End programmer edit section *** (ОтсутствиеСотрудника CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ОтсутствиеСотрудника : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОкончания;
        
        private System.DateTime fДатаНачала;
        
        private IIS.1.ТипыЗанятости fПричина;
        
        private IIS.1.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (ОтсутствиеСотрудника CustomMembers)

        // *** End programmer edit section *** (ОтсутствиеСотрудника CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ОтсутствиеСотрудника.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ОтсутствиеСотрудника.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.ДатаНачала Get start)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.ДатаНачала Get end)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.ДатаНачала Set start)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.ДатаНачала Set end)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ОтсутствиеСотрудника.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ОтсутствиеСотрудника.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.ДатаОкончания Get start)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.ДатаОкончания Get end)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.ДатаОкончания Set start)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.ДатаОкончания Set end)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// Причина.
        /// </summary>
        // *** Start programmer edit section *** (ОтсутствиеСотрудника.Причина CustomAttributes)

        // *** End programmer edit section *** (ОтсутствиеСотрудника.Причина CustomAttributes)
        public virtual IIS.1.ТипыЗанятости Причина
        {
            get
            {
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.Причина Get start)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.Причина Get start)
                IIS.1.ТипыЗанятости result = this.fПричина;
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.Причина Get end)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.Причина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.Причина Set start)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.Причина Set start)
                this.fПричина = value;
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.Причина Set end)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.Причина Set end)
            }
        }
        
        /// <summary>
        /// ОтсутствиеСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (ОтсутствиеСотрудника.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ОтсутствиеСотрудника.Сотрудник CustomAttributes)
        [PropertyStorage("Сотрудник")]
        [TypeUsage(new string[] {
                "IIS.1.Бригадир",
                "IIS.1.Работник",
                "IIS.1.Сотрудник"})]
        [NotNull()]
        public virtual IIS.1.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.Сотрудник Get start)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.Сотрудник Get start)
                IIS.1.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.Сотрудник Get end)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.Сотрудник Set start)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ОтсутствиеСотрудника.Сотрудник Set end)

                // *** End programmer edit section *** (ОтсутствиеСотрудника.Сотрудник Set end)
            }
        }
    }
}
