//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СоставБригады.
    /// </summary>
    // *** Start programmer edit section *** (СоставБригады CustomAttributes)

    // *** End programmer edit section *** (СоставБригады CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class СоставБригады : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.1.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (СоставБригады CustomMembers)

        // *** End programmer edit section *** (СоставБригады CustomMembers)

        
        /// <summary>
        /// СоставБригады.
        /// </summary>
        // *** Start programmer edit section *** (СоставБригады.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (СоставБригады.Сотрудник CustomAttributes)
        [PropertyStorage("Сотрудник")]
        [TypeUsage(new string[] {
                "IIS.1.Бригадир",
                "IIS.1.Работник",
                "IIS.1.Сотрудник"})]
        [NotNull()]
        public virtual IIS.1.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (СоставБригады.Сотрудник Get start)

                // *** End programmer edit section *** (СоставБригады.Сотрудник Get start)
                IIS.1.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (СоставБригады.Сотрудник Get end)

                // *** End programmer edit section *** (СоставБригады.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставБригады.Сотрудник Set start)

                // *** End programmer edit section *** (СоставБригады.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (СоставБригады.Сотрудник Set end)

                // *** End programmer edit section *** (СоставБригады.Сотрудник Set end)
            }
        }
    }
}
