//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТипыЗанятости.
    /// </summary>
    // *** Start programmer edit section *** (ТипыЗанятости CustomAttributes)

    // *** End programmer edit section *** (ТипыЗанятости CustomAttributes)
    public enum ТипыЗанятости
    {
        
        // *** Start programmer edit section *** (ТипыЗанятости.Отгул CustomAttributes)

        // *** End programmer edit section *** (ТипыЗанятости.Отгул CustomAttributes)
        Отгул,
        
        // *** Start programmer edit section *** (ТипыЗанятости.Работал CustomAttributes)

        // *** End programmer edit section *** (ТипыЗанятости.Работал CustomAttributes)
        Работал,
        
        // *** Start programmer edit section *** (ТипыЗанятости.Прогул CustomAttributes)

        // *** End programmer edit section *** (ТипыЗанятости.Прогул CustomAttributes)
        Прогул,
        
        // *** Start programmer edit section *** (ТипыЗанятости.Болел CustomAttributes)

        // *** End programmer edit section *** (ТипыЗанятости.Болел CustomAttributes)
        Болел,
        
        // *** Start programmer edit section *** (ТипыЗанятости.Отпуск CustomAttributes)

        // *** End programmer edit section *** (ТипыЗанятости.Отпуск CustomAttributes)
        Отпуск,
        
        // *** Start programmer edit section *** (ТипыЗанятости.Выходной CustomAttributes)

        // *** End programmer edit section *** (ТипыЗанятости.Выходной CustomAttributes)
        Выходной,
    }
}
