//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.1
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Таблица перехода состояний.
    /// </summary>
    // *** Start programmer edit section *** (УправляющийОбъектЗС CustomAttributes)

    // *** End programmer edit section *** (УправляющийОбъектЗС CustomAttributes)
    public class УправляющийОбъектЗС
    {
        
        private IIS.1.События fСобытия;
        
        // *** Start programmer edit section *** (УправляющийОбъектЗС CustomMembers)

        // *** End programmer edit section *** (УправляющийОбъектЗС CustomMembers)

        
        /// <summary>
        /// Таблица перехода состояний.
        /// </summary>
        // *** Start programmer edit section *** (УправляющийОбъектЗС.События CustomAttributes)

        // *** End programmer edit section *** (УправляющийОбъектЗС.События CustomAttributes)
        public virtual IIS.1.События События
        {
            get
            {
                // *** Start programmer edit section *** (УправляющийОбъектЗС.События Get start)

                // *** End programmer edit section *** (УправляющийОбъектЗС.События Get start)
                IIS.1.События result = this.fСобытия;
                // *** Start programmer edit section *** (УправляющийОбъектЗС.События Get end)

                // *** End programmer edit section *** (УправляющийОбъектЗС.События Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УправляющийОбъектЗС.События Set start)

                // *** End programmer edit section *** (УправляющийОбъектЗС.События Set start)
                this.fСобытия = value;
                // *** Start programmer edit section *** (УправляющийОбъектЗС.События Set end)

                // *** End programmer edit section *** (УправляющийОбъектЗС.События Set end)
            }
        }
    }
}
